name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.4

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Install the protoc-gen-gofast binary
      run: go get github.com/gogo/protobuf/protoc-gen-gofast && go install  github.com/gogo/protobuf/protoc-gen-gofast 

    - name: Generate certs
      run: go generate ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: GoGitOps Step  
      id: gogitops  
      uses: beaujr/gogitops-action@v0.2
      with:
        github-actions-user: owulveryck
        github-actions-token: ${{secrets.GITHUB_TOKEN}}
